[package]
name = "command-engine"
version = "0.6.0"
authors = ["FssAy <49795742+DmitrijVC@users.noreply.github.com>"]
edition = "2018"

[lib]
path = "src/command-engine.rs"

[dependencies]
async-trait = "0.1.9"
lazy_static = "1.4.0"

[dependencies.tokio]
version = "1.9.0"
features = [
    "rt-multi-thread",
    "sync",
    # "full",
]

[features]
default = []
full = []
